package com.merold.civcalcs.buildings;

public enum Outputs {
	CULTURE,FOOD,FAITH,SCIENCE,PRODUCTION,GOLD,HAPPINESS,GROWTH_FOOD,GE_POINTS,GS_POINTS,GMERCH_POINTS,GA_POINTS,GW_POINTS,GMUSC_POINTS,
	GE_BONUS_POINTS,GS_BONUS_POINTS,GMERCH_BONUS_POINTS,GA_BONUS_POINTS,GW_BONUS_POINTS,GMUSC_BONUS_POINTS,TOURISM
}
